### ISSUE TITLE
Check Entrez-gene test

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/WikiPathwaysCurator#10]
See [general test](https://github.com/BiGCAT-UM/WikiPathwaysCurator/blob/master/src/test/java/nl/unimaas/bigcat/wikipathways/curator/Genes.java); is this test able to pick up spaces/characters which shouldn't be part of an ID?

See the example in this PW:
![image](https://user-images.githubusercontent.com/26277832/73732782-0faf2300-473b-11ea-9a6c-2220a8ad6315.png)

This lead to the following line in the RDF:
```
dc:identifier       <http://identifiers.org/ncbigene/5524
                5524> ;
```
Which gave the following error in Blazegraph trying to upload the Jenkins All_Dev from #2235 (last one which ran before the servers where shut down):

```
java.util.concurrent.ExecutionException: org.openrdf.rio.RDFParseException: IRI included an unencoded space: '32' [line 2143066]
```

I'll fix the ID in the PW now, but would be good to check if we have a test which can detect these things.

**Comment by egonw** [comment]
Covered by `GeneTests.entrezGeneIdentifiersNotNumber()`.
