### ISSUE TITLE
write a test to detected Wikidata identifiers that no longer map #nwobridgedb

### ISSUE THREAD

**Issue by egonw** [wikipathways/WikiPathwaysCurator#23]

**Comment by egonw** [comment]
@tabbassidaloii, you said something related to this, right?

**Comment by tabbassidaloii** [comment]
> @tabbassidaloii, you said something related to this, right?

we now have secondary to primary ID mapping for wikidata both as a [tsv file](https://github.com/tabbassidaloii/create-bridgedb-secondary2primary/blob/main/output/wikidata_secIds.tsv) and a derby database

**Comment by egonw** [comment]
Implemented!

**Comment by egonw** [comment]
![image](https://user-images.githubusercontent.com/26721/201543669-3f386e6f-0103-4049-a35f-42773ab8ad49.png)
