### ISSUE TITLE
Automated check for IDs with source "other"

### ISSUE THREAD

**Issue by danidi** [wikipathways/WikiPathwaysCurator#27]
https://classic.wikipathways.org/index.php?title=Pathway:WP5385&oldid=126704 contains Ca+ wrongly added as gene product instead of metabolite. While it is probably not possible to automatically check for this mismatch directly, an alternative would be the following:  the ChEBI ID is provided as type "other", as ChEBI is not available for gene products. Identifying "other" datasources could help identify such errors, and maybe also show data sources that were used by pathway authors that could be added to the known sources.

**Comment by egonw** [comment]
I have a query now: https://bit.ly/3XrBJoI
