### ISSUE TITLE
Exception for nonMetaboliteToMetaboliteConversion test?

### ISSUE THREAD

**Issue by danidi** [wikipathways/WikiPathwaysCurator#28]
I think https://identifiers.org/uniprot/P05067 to https://identifiers.org/chebi/CHEBI:64645 would be a valid nonMetaboliteToMetaboliteConversion. It is Amyloid-beta precursor protein to amyloid-beta.

**Comment by egonw** [comment]
Okay, I added it. This should fix the false positives you have seen. If not, please report here, reopen it, and give me a pointer to the false positive, plz.
