### ISSUE TITLE
Check protein-protein conversion: false positive

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/WikiPathwaysCurator#7]
Should be modulation iso conversion suggestions for test:

https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Curation%20(WP2RDF%20Curation)%20(all,%20dev)/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Interactions/noProteinProteinConversions/

 http://www.wikipathways.org/instance/WP4524_r103280

**Comment by egonw** [comment]
Believed to be fixed.
